action_id: trunk-single-player-auto-on-upgrade
date: 2023-10-14 19:41:47
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1697312507
full_timestamp:
  nanos: 292995000
  seconds: 1697312507
trunk_version: 1.16.2
