action_id: trunk-cache-prune
date: 2023-10-10 15:34:14
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1696952054
full_timestamp:
  nanos: 798023000
  seconds: 1696952054
trunk_version: 1.16.2
