action_id: trunk-cache-prune
date: 2023-10-25 12:56:26
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1698238586
full_timestamp:
  nanos: 238215000
  seconds: 1698238586
trunk_version: 1.16.2
