action_id: trunk-share-with-everyone
date: 2023-10-04 18:17:59
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1696443479
full_timestamp:
  nanos: 291265000
  seconds: 1696443479
trunk_version: 1.16.2
